### ISSUE TITLE
小建议，少部分节点无法拉取baomitu静态资源，是否可以考虑能设置本地拉取或从三方资源库拉取

### ISSUE THREAD

**Issue by zhaxidelei789** [netcccyun/dnsmgr#1]
RT，不知道下个版本发布时是否可在安装处和安装后都可以在后台可以管理设置css js静态资源的拉取方式（本地或第三方），感谢大佬的开源作品，愿意捐赠支持

**Comment by netcccyun** [comment]
哪里无法拉取baomitu静态资源？

**Comment by zhaxidelei789** [comment]
> 哪里无法拉取baomitu静态资源？

感谢大佬百忙之中回复，我观察了一下，有时候同一个节点baomitu会拉取不了有时候可以，香港英国美国都有遇到过，有时候又可以。仅仅反馈一下使用中遇到的问题，能增加选择本地最好，不能也可以理解，感谢彩虹大佬的作品

**Comment by famousprince** [comment]
考虑下切换到 cdnjs.cloudflare.com/ajax/libs 或者 s4.zstatic.net/ajax/libs ?

**Comment by hoey94** [comment]
同样遇到这个问题，排查发现所有的静态资源都访问不了了，导致无法使用bootstrap相关类库
https://s4.zstatic.net/ajax/libs/bootstrap-table/1.21.4/bootstrap-table.min.js
修改文件第21就可以了
```
vim web/app/middleware/ViewOutput.php

View::assign('cdnpublic', 'https://cdnjs.cloudflare.com/ajax/libs/');
````
