### ISSUE TITLE
SSL证书代理 CNAME代理无法增加 选项BUG

### ISSUE THREAD

**Issue by winnerzyy** [netcccyun/dnsmgr#100]
![00566282-f692-4c18-9773-f7dee6bc052f](https://github.com/user-attachments/assets/9061d592-dad7-4e4d-af36-dcc71594746e)
SSL证书代理 CNAME代理无法增加 选项BUG  如图

**Comment by netcccyun** [comment]
那是你还没在域名管理添加域名
