### ISSUE TITLE
TCP探测端口大于128时异常

### ISSUE THREAD

**Issue by HanadaLee** [netcccyun/dnsmgr#12]
![image](https://github.com/netcccyun/dnsmgr/assets/33758411/c6f7de34-dacb-4d99-b3e3-5a4c5fd8a97c)
![image](https://github.com/netcccyun/dnsmgr/assets/33758411/ae5767d4-463d-40f8-bad7-2e9820e40e62)
![image](https://github.com/netcccyun/dnsmgr/assets/33758411/9004d4b2-469a-484f-8b9a-b8d45a26d6db)

```
[2024-04-22T10:41:10+08:00][error] [10501]SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'tcpport' at row 1[/var/www/html/vendor/topthink/think-orm/src/db/PDOConnection.php:797]
```

**Comment by xieruan** [comment]
[  `tcpport` tinyint(5) DEFAULT NULL,](https://github.com/netcccyun/dnsmgr/blob/8d653b872a32d06ae41a88b5d383675ff97970d9/app/sql/install.sql#L89)     确实，tinyint 的取值范围是从 -128 到 127

**Comment by HanadaLee** [comment]
https://github.com/netcccyun/dnsmgr/commit/8f257664aedafc12a1e6cc32dc115b5ea1fa87db 1.2.1已修复 

附更新sql数据库语句
ALTER TABLE `dnsmgr_dmtask` MODIFY COLUMN `tcpport` int(5) DEFAULT NULL;
