### ISSUE TITLE
希望实现容灾切换兜底策略

### ISSUE THREAD

**Issue by HanadaLee** [netcccyun/dnsmgr#17]
![image](https://github.com/netcccyun/dnsmgr/assets/33758411/716fe3ef-fcac-4ab8-a0cd-96c218045190)

目前在识别到IP不可用后有三个可能的操作，其中暂停解析主要是用于当某个IP不可用时剔除IP，其他IP继续服务的场景，但极端情况（可能是配置错误或探测端自身网络问题等）下可能会出现所有IP都被剔除，导致域名无法解析。因此希望增加兜底策略，以下是一些建议的兜底策略：

基础实现：
1. 在识别到本记录是最后一个启用的解析记录，且该记录探测出现异常时，本次不执行暂停解析操作
2. 在识别到本记录是最后一个启用的解析记录，且该记录探测出现异常时，强制启用所有暂停的同名解析记录
3. 在识别到本记录是最后一个启用的解析记录，且该记录探测出现异常时，切换备用解析

进阶实现：
可以考虑采用引入异常比例阈值，比如有5个同名解析记录，异常比例设置为40%，如果异常解析记录大于40%（也就是3个故障）时，第3个开始不再暂停解析，或者大于40%时整体切换到备用解析。不过这个要实现可能需要重构一下探测任务的逻辑了，现在探测任务是以单个解析记录为单位做的，如果要实现比例可能要把探测任务的实现粒度改为域名粒度，单个探测任务同时对该域名下的所有A记录、AAAA记录、CNAME记录做探测。

以上是我的一些建议，仅供参考。

**Comment by netcccyun** [comment]
你说的这些太复杂了，搞个最简单的就是，新增一个“自动开启解析”类型的策略，默认是暂停解析状态，当检测到同域名记录数量减少到指定值的时候自动开启。

**Comment by HanadaLee** [comment]
> 你说的这些太复杂了，搞个最简单的就是，新增一个“自动开启解析”类型的策略，默认是暂停解析状态，当检测到同域名记录数量减少到指定值的时候自动开启。

对，简单来说这种就可以，对于一般用途基本够了，只要防止出现没有ip可解析的情况就行

**Comment by Scholar-m** [comment]
这个功能至今我没用成功过
