### ISSUE TITLE
CF优选IP提示服务器错误

### ISSUE THREAD

**Issue by 56025192** [netcccyun/dnsmgr#18]
CF优选IP提示服务器错误
![image](https://github.com/netcccyun/dnsmgr/assets/39239064/75b7af84-c778-402c-af79-a90c03ce3a3c)
![image](https://github.com/netcccyun/dnsmgr/assets/39239064/eab158c9-855a-494a-b243-e2665fb11f5a)

**Comment by netcccyun** [comment]
我试了没问题，你去首页点清除缓存试试呢

**Comment by 56025192** [comment]
![image](https://github.com/netcccyun/dnsmgr/assets/39239064/c651f1a9-35c6-46fb-86e1-b017740abfd9)

**Comment by netcccyun** [comment]
那你重新下载试试

**Comment by wang4386** [comment]
我也是提示服务器错误，也尝试过清理缓存

**Comment by gacjie** [comment]
实在没法用 
可以试试这个项目
https://github.com/gacjie/cf2dns/

**Comment by netcccyun** [comment]
> 我也是提示服务器错误，也尝试过清理缓存

我这没出现过，你重新下载过吗

**Comment by wang4386** [comment]
> > 我也是提示服务器错误，也尝试过清理缓存
> 
> 我这没出现过，你重新下载过吗

重新下载过，在1panel上面部署的，php74，mysql8.2，容灾切换正常，就是域名优选一直提示服务器错误

**Comment by 56025192** [comment]
> > > 我也是提示服务器错误，也尝试过清理缓存
> > 
> > 
> > 我这没出现过，你重新下载过吗
> 
> 重新下载过，在1panel上面部署的，php74，mysql8.2，容灾切换正常，就是域名优选一直提示服务器错误

我也是1panel   估计是容器环境有问题

**Comment by wjn6** [comment]
> > > 我也是提示服务器错误，也尝试过清理缓存
> > 
> > 
> > 我这没出现过，你重新下载过吗
> 
> 重新下载过，在1panel上面部署的，php74，mysql8.2，容灾切换正常，就是域名优选一直提示服务器错误

有个监控你添加了吗，我记得1p好像没有这个功能
