### ISSUE TITLE
验证码问题

### ISSUE THREAD

**Issue by maxage** [netcccyun/dnsmgr#21]
![](https://image.dooo.ng/c/2024/05/05/66372ccf8e5dd.webp)
部署好后登录，不显示验证码。1panel安装的。

**Comment by netcccyun** [comment]
应该是缺少php组件

**Comment by jiuyue52** [comment]
需要安装gd扩展
![image](https://github.com/user-attachments/assets/cf5efb4b-29fb-4e18-902b-040a397fc7c3)
