### ISSUE TITLE
cf优选ip

### ISSUE THREAD

**Issue by Hockercat** [netcccyun/dnsmgr#22]
![image](https://github.com/netcccyun/dnsmgr/assets/154535240/5e2ed347-9e54-496e-9768-dd80eb7fe161)请问我这里为什么选择不了域名**

**Comment by netcccyun** [comment]
那是你没添加域名

**Comment by Hockercat** [comment]
添加了

**Comment by netcccyun** [comment]
你添加的域名是不是都是CF的？那肯定不行

**Comment by Hockercat** [comment]
那要怎么添加的

**Comment by wjn6** [comment]
> 那要怎么添加的

只能添加其他dns服务商的
