### ISSUE TITLE
从1.3版本更新到1.4版本之后，出现了问题

### ISSUE THREAD

**Issue by GH6324** [netcccyun/dnsmgr#28]
我是更新是直接从Releases上下载新版本然后解压替换的

PHP的版本是8.1

一开始更新完是能正常使用的，就这两天突然用不了；EDGE浏览器无痕模式下有时候能打开，有时候也不能打开

在换了Chrome浏览器也是一样的报错

后台首页能加载出来，但是控制台也有报错：
![image](https://github.com/netcccyun/dnsmgr/assets/47879885/a871bbd0-b374-4b39-9afc-16d206a5a672)

域名管理加载不出来，控制台报错如下：
![image](https://github.com/netcccyun/dnsmgr/assets/47879885/5232a976-e8b9-4b37-886c-1c01605b7b87)

排查了好久不知道是什么原因，烦请大佬看一下是什么问题

**Comment by netcccyun** [comment]
应该是有静态资源加载失败了，你可以换其他网络试试
