### ISSUE TITLE
无法添加域名账号

### ISSUE THREAD

**Issue by llkj0001** [netcccyun/dnsmgr#34]
![image](https://github.com/netcccyun/dnsmgr/assets/114677240/e6a857f3-c383-483d-aa53-aa4c9a0206c3)
![image](https://github.com/netcccyun/dnsmgr/assets/114677240/ad1a39e6-6f0c-4966-88c9-7ba4a095a542)

如图所示，我生成的api令牌允许dns读写

**Comment by dishao123** [comment]
你好，我也遇到了同样的问题，麻烦能说一下怎么解决的吗？
