### ISSUE TITLE
是否可以支持优选IP

### ISSUE THREAD

**Issue by gacjie** [netcccyun/dnsmgr#4]
目前很多建站用户使用CloudFlare CloudFront Gcore等cdn
默认分配的IP国内访问不佳，希望站长能支持获取优选IP并自动化更新到解析中。

支持cf优选的平台有
https://stock.hostmonit.com/CloudFlareYes
接口是
https://api.hostmonit.com/get_optimization_ip
需要post提交{"key": KEY, "type": TYPE}
项目地址github.com/ddgth/cf2dns

https://monitor.gacjie.cn/
接口是https://monitor.gacjie.cn/api/client/get_ip_address
需要post/get提交{"key": config["key"], "type":iptype, "cdn_server": config["cdn_server"]}
项目地址github.com/gacjie/cf2dns

**Comment by netcccyun** [comment]
你这个优选IP的代码有问题吧，只设置了电信、联通、移动的解析记录，这样国内其他线路还是用不到优选IP（比如教育网、搜索引擎）

**Comment by gacjie** [comment]
代码没有问题
因为cf是泛播路由 同一个IP地址三网访问的节点机房是不同的
移动联通电信需要这些线路的服务器单独测IP
教育网 广电这些 没有测速服务器 想搞也搞不来
搜索引擎 这个一般都是用户单独设置的
其次是默认线路一般都会解析到cf SAAS回退源地址 或者CNAME地址上去 而且国外使用默认地址也不差
因此目前只能支持 移动 联通 电信 三网优选IP 自动化更新
