### ISSUE TITLE
支持申请SSL证书

### ISSUE THREAD

**Issue by rong6** [netcccyun/dnsmgr#41]
支持申请免费的SSL证书，如Let's Encrypt

**Comment by coolxitech** [comment]
你要找的是不是[Certd](https://github.com/certd/certd)？

**Comment by rong6** [comment]
> 你要找的是不是[Certd](https://github.com/certd/certd)？

这个玩意不好用，[Certimate](https://github.com/usual2970/certimate)或许是更好的完全开源解决方案，之前想要这个DNS管理系统支持申请证书完全是为了更加方便添加解析，现在没什么必要了，故关闭issue

**Comment by coolxitech** [comment]
> > 你要找的是不是[Certd](https://github.com/certd/certd)？
> 
> 这个玩意不好用，[Certimate](https://github.com/usual2970/certimate)或许是更好的完全开源解决方案，之前想要这个DNS管理系统支持申请证书完全是为了更加方便添加解析，现在没什么必要了，故关闭issue

一个半成品就别吹了
