### ISSUE TITLE
对接了Cloudflare的域名，有个别域名看不到解析条目

### ISSUE THREAD

**Issue by yangyzp** [netcccyun/dnsmgr#45]
1.6最新版，对接了Cloudflare的域名解析有2个域名里的解析无法获取，显示空的，但是从cf官网进去，是有解析了。
聚合dns后台也能正常添加删除这个域名，但是就看不到解析了，其他域名正常。

在聚合dns后台增加这个域名的解析后，里面看不到这个新增加的解析，但是去cf后台能看到刚才在聚合dns后台增加这个域名的解析。
说明聚合dns后台可以操作这个域名增加解析了，但是却看不到~~~

如下图，域名大码了，是同一个域名
![PixPin_2024-07-23_22-48-53](https://github.com/user-attachments/assets/2bea671c-f9e1-454c-8acb-1cac73ec9a97)

**Comment by yangyzp** [comment]
重新安装了，打乱顺序重新添加域名，添加到这个前面看不到解析的域名的时候，又是它看不到解析，其他正常的还是正常，感觉程序像是触发关键词把这个域名屏蔽一样~~（和这效果差不多~~）

**Comment by feithink** [comment]
同样遇到这个问题。部分域名不能成功获取到解析记录，之前能获取到的解析的域名，现在也不能获取了。

**Comment by netcccyun** [comment]
感觉像是列表接口有报错，你可以F12看看接口返回的什么

**Comment by netcccyun** [comment]
好了，CF最近改了返回参数

**Comment by akiker233** [comment]
我也是这样

**Comment by Scholar-m** [comment]
我也一样，你们是怎么解决的？
