### ISSUE TITLE
华为云cn域名添加解析失败

### ISSUE THREAD

**Issue by skoy03** [netcccyun/dnsmgr#50]
华为云添加新的解析失败
![QQ截图20240828174023](https://github.com/user-attachments/assets/a02c44a1-0405-414b-aa15-7ba76eb8b0f2)
![QQ截图20240828174104](https://github.com/user-attachments/assets/e6c9a10e-9c3b-43e0-ad03-8ac4fdd8f9f2)

另外华为云的TTL可以支持最小1毫秒.但是修改解析的时候却需要最小600,希望能更新下

**Comment by skoy03** [comment]
应该说华为云的TTL最小支持1秒

**Comment by netcccyun** [comment]
我刚才试了没问题，看上去是你这个线路查询失败了
