### ISSUE TITLE
实测阿里云添加MX解析记录会报错

### ISSUE THREAD

**Issue by dpifox** [netcccyun/dnsmgr#51]
![QQ20240829-105609](https://github.com/user-attachments/assets/d4f85fc5-7c5e-4ca4-a6cb-d4a2080660bf)

域名托管在阿里云，添加mx解析时出现这个报错。

实测腾讯云可以正常添加，其他的不知道

**Comment by dpifox** [comment]
当前版本：V1.7 (Build 1013)

**Comment by tyjsjxh** [comment]
似乎是因为阿里云已经不能按照秒来设置了
![360截图20240924183747](https://github.com/user-attachments/assets/cdd79367-7f32-42cc-9d65-34617ef6b1a7)

**Comment by tyjsjxh** [comment]
阿里云设置TTL为秒需要企业版DNS
