### ISSUE TITLE
monitor.gacjie.cn接口域名更换通知

### ISSUE THREAD

**Issue by gacjie** [netcccyun/dnsmgr#60]
不好意思，最近因为一些原因把域名换了。
本来打算用小姨子域名的，但是那个域名已经做公共优选CNAME地址了。
怕域名被污染，所以重新买了个wetest.vip提供服务。
麻烦作者抽空更换一下新域名。
www.182682.xyz域名暂时不受影响，但半个月后会301到www.wetest.vip以便集中权重。

**Comment by 2duat** [comment]
你这是广告吧！

**Comment by gacjie** [comment]
> 你这是广告吧！

不是广告
cdn优选IP的数据是由第三方网站提供的

其中我的网站wetest.vip提供了 CloudFlare 、 CloudFront 、Gcore的优选IP数据
hostmonit.com 提供了 CloudFlare 的优选IP数据
345673.xyz提供了 CloudFlare 的优选IP数据但目前已经废弃作者已经不提供了

如果只想要自动更新优选IP可以看一下我的另一个项目
https://github.com/gacjie/cf2dns
