### ISSUE TITLE
可否为域名账户添加代理支持，cloudflare国内无法访问

### ISSUE THREAD

**Issue by oozzbb** [netcccyun/dnsmgr#63]
![1728222214905](https://github.com/user-attachments/assets/f6095293-44f8-4fb4-af0e-4724da79cedc)
目前是手动直接改的代码

**Comment by netcccyun** [comment]
cloudflare我试了国内可以访问

**Comment by yueyue5201314** [comment]
@oozzbb cloudflare的api又没有被墙，怎么可能无法访问……我日常管理全是裸连
