### ISSUE TITLE
优选IP任务“每条线路解析数量”配置无效果？

### ISSUE THREAD

**Issue by yueyue5201314** [netcccyun/dnsmgr#66]
优选ip任务的配置，“每条线路解析数量”选项没有效果。无论设置为几，都只会一条线路添加一条解析记录，而且这条解析记录会包含所有优选ip……

**Comment by netcccyun** [comment]
你是说华为云吧，华为云不限制解析IP数量，所以就默认包含所有的了

**Comment by yueyue5201314** [comment]
> 你是说华为云吧，华为云不限制解析IP数量，所以就默认包含所有的了

哦，好的！我还以为这个功能没效果[捂脸]
