### ISSUE TITLE
根本搜索不了域名

### ISSUE THREAD

**Issue by adam88888888** [netcccyun/dnsmgr#70]
根本搜索不了域名，只能加载几条，还要不断往下拉，很鸡肋

**Comment by netcccyun** [comment]
我试了大多数DNS服务商都可以搜索

**Comment by adam88888888** [comment]
![微信截图_20241030194047](https://github.com/user-attachments/assets/c8b93362-debf-4c9c-b0b6-de200b4e880e)
直接输入已经显示的域名都搜不了，一次只显示十条域名，几百条的根本加载不出来，搜什么

**Comment by adam88888888** [comment]
你只是进去点域名而已，根本没用过搜索域名这个功能吧？

**Comment by netcccyun** [comment]
用过啊，就在添加的时候，输入框里面输入域名，然后自动搜索

**Comment by adam88888888** [comment]
根本就搜不了

**Comment by adam88888888** [comment]
要一直往下拉才能显示其他域名，搜个屁
