### ISSUE TITLE
CloudFlare MX优先级设置无效

### ISSUE THREAD

**Issue by xueba0458** [netcccyun/dnsmgr#74]
CloudFlare MX优先级设置无效，无论是添加时配置MX优先级，还是添加后修改MX优先级都会变成0！！！不仅仅是显示为0，实际解析记录的MX优先级也是0
![image](https://github.com/user-attachments/assets/1628a730-cb3c-4e6c-87e1-704d5a19c0a4)
手动在Cloudflare 控制台修改记录后能够正常显示
![image](https://github.com/user-attachments/assets/772d02d4-586c-4e9c-8672-fab3e2950116)

**Comment by coolxitech** [comment]
作者把参数位置写错了，我在自己的分支修复了.
