### ISSUE TITLE
期待添加转发访问DNS功能

### ISSUE THREAD

**Issue by eoer** [netcccyun/dnsmgr#76]
感谢大佬开源这个项目,一直以来我都拿它来管理吃灰的域名.
但是目前有个需求,就是访问DNS服务商的API时能否添加一个转发功能呢?
比如使用Cloudflare workers去请求DNS的api,
这样能有效解决仅服务器IP去访问dns api的问题,对于多用户多域名管理,
如果都是相同的IP请求API,其中有一个用户的域名出现问题,其他用户的域名很容易被连带封禁.

**Comment by netcccyun** [comment]
域名封禁和请求API的IP也有关系？什么平台的域名会这样

**Comment by eoer** [comment]
> 域名封禁和请求API的IP也有关系？什么平台的域名会这样

腾讯的dnspod会的,一般请求API的地址相同基本都视为同一用户禁掉

**Comment by netcccyun** [comment]
已增加代理功能
