### ISSUE TITLE
容灾策略@主机名获取不到记录值

### ISSUE THREAD

**Issue by jrz233** [netcccyun/dnsmgr#8]
对接的华为云的，@记录获取不到，其他的二级可以获取到

**Comment by xieruan** [comment]
主机记录不要留空 填写 @ 就能获取到，或者劳烦开发者 写一个检测，空值就默认为 @
https://github.com/netcccyun/dnsmgr/blob/8d653b872a32d06ae41a88b5d383675ff97970d9/app/view/dmonitor/taskform.html#L179
