### ISSUE TITLE
CF解析数量有点问题

### ISSUE THREAD

**Issue by wwdmy123** [netcccyun/dnsmgr#80]
![image](https://github.com/user-attachments/assets/869a0d3e-ea30-43a6-ae47-d89454da095a)
如图所示

**Comment by wwdmy123** [comment]
测试下来解析的是多个ip
![image](https://github.com/user-attachments/assets/8dc67727-f858-43ec-86a9-dca11e5913fb)

**Comment by netcccyun** [comment]
华为云默认就是这样，因为不限IP数量

**Comment by wwdmy123** [comment]
> 华为云默认就是这样，因为不限IP数量

好的，知道了。感谢大佬
