### ISSUE TITLE
访问域名记录报错

### ISSUE THREAD

**Issue by hoey94** [netcccyun/dnsmgr#81]
问题： 在访问复杂的记录时，会出现展示问题
错误日志: 
<img width="1468" alt="image" src="https://github.com/user-attachments/assets/0d8ebbdd-fa5a-4194-8c4b-52a8fdcfce53" />

场景还原： 准备一个域名，域名里面按照下图进行设置
<img width="1553" alt="image" src="https://github.com/user-attachments/assets/e05a7329-bf72-479d-8de0-252b5c0e15c1" />
随后在 DNS中访问列表【域名管理】-> 【点击添加好的域名】，在查看记录时报错。

**Comment by xuxiaolei** [comment]
我也遇到这个问题，之前都是好的，今天突然就无法展示了，有点莫名其妙，解析记录也不多，没有复杂的解析
![image](https://github.com/user-attachments/assets/7a35f554-3057-472a-ab09-8ebc877dffe1)
![90854665-8A7D-4F66-BC51-D4577C379D0B](https://github.com/user-attachments/assets/3dfc74dd-6504-4e34-84aa-9cdac034c367)
![20241218170051](https://github.com/user-attachments/assets/6765e96e-bdd6-4c85-b49d-c9944a476d1e)

**Comment by xuxiaolei** [comment]
试了一下，应急的话，可以将app/lib/dns/aliyun.php下的updatetime取值逻辑修改加上*1000就行了
![image](https://github.com/user-attachments/assets/254723a8-bb6b-44df-9b16-306673e24781)
![image](https://github.com/user-attachments/assets/84318451-4ee7-4642-be3a-9828f16ce4c4)
docker部署的话：
docker exec -it dnsmgr bash
cd /app/www/app/lib/dns
vi vi aliyun.php 
修改：date('Y-m-d H:i:s', $row['UpdateTimestamp']*1000/1000)
:wq 保存

**Comment by xuxiaolei** [comment]
您的邮件我已经收到，感谢你的来信
