### ISSUE TITLE
希望老大修改支持分省解析，实现智能DNS解析功能，这个是最流行的

### ISSUE THREAD

**Issue by haozhengtu** [netcccyun/dnsmgr#82]
老板希望修改支持智能分省分线路等智能解析操作，这样适合真正的站长们使用

**Comment by netcccyun** [comment]
阿里云腾讯云这些都支持，开通高级版DNS套餐就有了

**Comment by unclegpts** [comment]
@netcccyun 青云DNS支持智能分省分线路解析。

**Comment by adam88888888** [comment]
> 阿里云腾讯云这些都支持，开通高级版DNS套餐就有了

花钱谁不知道有，说这废话

**Comment by kiko923** [comment]
> > 阿里云腾讯云这些都支持，开通高级版DNS套餐就有了
> 
> 花钱谁不知道有，说这废话

dns又不是彩虹的 你站着说话不腰疼？不付费谁给你提供分线解析 低能 人家只是写一个调用接口方便用 你还提上要求了 没脑子一边去
