### ISSUE TITLE
跨域问题？

### ISSUE THREAD

**Issue by madlaxcb** [netcccyun/dnsmgr#88]
docker安装后这部分无法正常显示

![图片](https://github.com/user-attachments/assets/a043632c-830d-415d-8285-5cc45cf2cee5)
![图片](https://github.com/user-attachments/assets/2f154b77-2d82-446c-964c-feb0d7f5d46c)

**Comment by netcccyun** [comment]
这个刷新缓存就行，前几天刚跟CDN反馈了，可能还有部分节点有缓存
