### ISSUE TITLE
华为云申请证书时验证，所有值要写在一个记录里

### ISSUE THREAD

**Issue by wjn6** [netcccyun/dnsmgr#91]
华为云申请证书时验证，所有值要写在一个记录里，
例如
"xxxxx"
"ccccc"
中间回车隔开

**Comment by netcccyun** [comment]
你这是申请泛域名证书，要添加2个同主机记录的TXT记录？

**Comment by wjn6** [comment]
> 你这是申请泛域名证书，要添加2个同主机记录的TXT记录？

是的

**Comment by netcccyun** [comment]
我试了写在一个记录里面，Let's Encrypt也识别不了

**Comment by wjn6** [comment]
> 我试了写在一个记录里面，Let's Encrypt也识别不了

![fd65254530e432f81bca7e97cdcaa83b](https://github.com/user-attachments/assets/0c956968-af85-44a6-bef9-c513a3a611a8)
像这样填写就可以

**Comment by netcccyun** [comment]
已修复
