### ISSUE TITLE
添加域名的时候能全部导入么

### ISSUE THREAD

**Issue by adam88888888** [netcccyun/dnsmgr#92]
几百个域名不知道要加到什么时候

**Comment by netcccyun** [comment]
已增加该功能

**Comment by adam88888888** [comment]
> 已增加该功能

获取域名列表失败，Curl error: OpenSSL SSL_connect: Connection reset by peer in connection to api.dns.la:443
域名太多的时候会显示失败，重新再点获取域名，前面的域名就没有了

**Comment by adam88888888** [comment]
> 已增加该功能

![wechat_2024-12-31_063410_964](https://github.com/user-attachments/assets/ff8ef390-dd7f-4e70-a2ad-38485a73cbc0)
域名太多无法添加

**Comment by netcccyun** [comment]
> > 已增加该功能
> 
> ![wechat_2024-12-31_063410_964](https://private-user-images.githubusercontent.com/144252965/399380738-ff8ef390-dd7f-4e70-a2ad-38485a73cbc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2MTk4NjMsIm5iZiI6MTczNTYxOTU2MywicGF0aCI6Ii8xNDQyNTI5NjUvMzk5MzgwNzM4LWZmOGVmMzkwLWRkN2YtNGU3MC1hMmFkLTM4NDg1YTczY2JjMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMVQwNDMyNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OGI3MmM0Yzc3OWQyYjdiZWVlZjY4YzM5YjNlMmYzZTU1YzQ1MTk2MDMzMjQ4ZmFiZDQ1Zjk2ODU2NmMwM2QzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.z3cbzWMqEHe05tdPt8XsybcGSmMrHQlJEBKe7YroB7g) 域名太多无法添加

你这是多少
