### ISSUE TITLE
自动部署任务能否支持一次性添加多个域名

### ISSUE THREAD

**Issue by kiko923** [netcccyun/dnsmgr#95]
自动部署任务能否支持一次性添加多个域名 或者从腾讯云cdn接口获取l列表 提供多选框
![1734940314015](https://github.com/user-attachments/assets/4997e82a-1a53-4f25-859a-b2f07b9baf1c)

**Comment by kiko923** [comment]
逗号添加多个能增多一个换行吗

**Comment by netcccyun** [comment]
已经支持逗号分隔了
