### ISSUE TITLE
腾讯云cdn自动部署任务报错

### ISSUE THREAD

**Issue by kiko923** [netcccyun/dnsmgr#96]
域名一切正常存在腾讯云cdn中 但是无法部署到cdn 同域名的www.znnu.com却又可以
![1734940501794](https://github.com/user-attachments/assets/66dc9df1-556f-4265-a5be-acb57bef2f73)
![1734940534282](https://github.com/user-attachments/assets/bb22050e-821d-4052-b2c4-7e795058b7f6)

**Comment by kiko923** [comment]
问题已经找到 在添加域名的时候 我只写了*.znnu.com 用过其他厂商的 会自动把根域名也添加上去 但是这个是根据填了什么就是什么来生成ssl证书 希望能加上 如果是泛解析证书 默认加入根域名进去
![1734941430669](https://github.com/user-attachments/assets/4b374042-ccc0-44fd-9741-18ac612c4e18)

**Comment by netcccyun** [comment]
你申请证书的时候，填写什么域名最终证书就是什么域名。只写了*.znnu.com，那肯定不会带有znnu.com

**Comment by kiko923** [comment]
> 你申请证书的时候，填写什么域名最终证书就是什么域名。只写了*.znnu.com，那肯定不会带有znnu.com

如果是泛解析 能适配自动添加根域名吗 其他域名则是填什么就是什么

**Comment by wxDadadada** [comment]
> > 你申请证书的时候，填写什么域名最终证书就是什么域名。只写了*.znnu.com，那肯定不会带有znnu.com
> 
> 如果是泛解析 能适配自动添加根域名吗 其他域名则是填什么就是什么

申请的时候都填上去就好了znnu.com *.znnu.com这样申请 就带上了

**Comment by kiko923** [comment]
> > > 你申请证书的时候，填写什么域名最终证书就是什么域名。只写了*.znnu.com，那肯定不会带有znnu.com
> > 
> > 
> > 如果是泛解析 能适配自动添加根域名吗 其他域名则是填什么就是什么
> 
> 申请的时候都填上去就好了znnu.com *.znnu.com这样申请 就带上了

我知道 就是懒 哈哈哈哈哈
