### ISSUE TITLE
[BUG] Cloudflare的Workers记录中的地址显示异常

### ISSUE THREAD

**Issue by TheresaQWQ** [netcccyun/dnsmgr#97]
如题，截图如下：
![image](https://github.com/user-attachments/assets/8c9eb0aa-dbe5-451c-bece-cea83927af7f)
![image](https://github.com/user-attachments/assets/c0b589e4-121a-4a86-9be9-7a5bb244ea81)

**Comment by netcccyun** [comment]
worker的记录就是这样
